# -*- coding: utf-8 -*-
"""Histogram-v5 csv - 3 columns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZLeIGijMB8LUEN7yQ1n5OHDXNhGwioAc
"""

import pandas as pd
import matplotlib.pyplot as plt
import io
from google.colab import files

#Uploader
uploaded = files.upload()
data = pd.read_csv(io.BytesIO(uploaded['6.csv']))

df = pd.DataFrame(data, columns=['Burner','Inlet Bed','PRESSURE'])

# Convert the 'Pressure' column to numeric, coercing errors to NaN
df2 = df.apply(pd.to_numeric, errors='coerce')

df2.describe()
df2.columns

print(df2.describe())
print("Shape:", df2.shape)
print("\nData Types:\n", df2.dtypes)
print("\nMissing Values:\n", df2.isnull().sum())
print("\nSummary Statistics:\n", df2.describe(include='all'))

df3 = pd.DataFrame(df2, columns=['Burner'])
x = df3
plt.hist(x,bins=10)

#plt.plot(label=Day 1)
plt.xlabel("Temperature ° C")
plt.ylabel("Count")
plt.title("RPOS CC L8S STS Histogram - Burner Temperature")
plt.legend()

plt.show()

#df2 = pd.DataFrame(data, columns=['DATE'])
#print(df2.iloc[0])