# -*- coding: utf-8 -*-
"""Histogram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O--gL58v6XyrIf7zAJVNcZD7-qsDaASD
"""

import pandas as pd
import matplotlib.pyplot as plt
import io

from google.colab import files

uploaded = files.upload()

data = pd.read_excel(io.BytesIO(uploaded['307..xlsx']))

df = pd.DataFrame(data, columns=['307'])
x = df

plt.hist(x,bins=10)

plt.show()
print(df.describe())

#df2 = pd.DataFrame(data, columns=['DATE'])
#print(df2.iloc[0])